languageCode = "pl-PL"
title = "Raporty"
baseURL = "https://lepszyweb.github.io/raporty/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Testowe raporty z badania dostępności"
  codePenUser = ""
